### ISSUE TITLE
fisher bug

### ISSUE THREAD

**Issue by NiallJeffrey** [justinalsing/delfi#5]
In "score/score.py", line 121 should be:

`if F is None:
      self.compute_fisher()`

At the moment it is set to `none`, which, if I remember, was a placeholder once?

**Comment by justinalsing** [comment]
Hi Niall,

Actually this is intentional - all of the ingredients might not be present yet for computing the Fisher matrix on initialization, eg., there are functions in the Gaussian score class to run simulations in parallel (MPI) for estimating the covariance, derivatives, etc needed for the Fisher matrix. So at the moment the onus is on the user to either pass a pre-computed Fisher matrix on initialization, or call compute_fisher() once all of the ingredients are in place (the mean, covariance, and both/either derivatives of the mean and covariance wrt the parameters)

**Comment by NiallJeffrey** [comment]
The problem with this is that the following code just produces a generic linalg-type 'none' error when calling the "scoreMLE".

`gaussian_score = score.Gaussian(ndata=len(fake_data),
                                theta_fiducial = np.array([om_mean, s8_mean]), 
                                mu = fiducial_band_power, Cinv = Cinv, dmudt = dmdt)`
`compressed_fake_data =  gaussian_score.scoreMLE(fake_data)`

I think if you want to leave line 121 as it is, then scoreMLE should return a sensible message if the Fisher matrices are still 'none'

**Comment by justinalsing** [comment]
Ok good idea - I've just added a line to spit out an error message if the user tries to call scoreMLE() before they have computed the fisher matrix (pushed just now)
